server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    access_log /var/log/nginx/phe-mobile-access.log;
    error_log /var/log/nginx/phe-mobile-error.log warn;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/phe-acme;
        default_type text/plain;
    }

    location / {
        return 308 https://$host$request_uri;
    }
}
